// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PV6yYGxZQsOGzt0NGUxXH-eeKio3WQQ',
    appId: '1:380145632021:web:5c4d876664058112385f1c',
    messagingSenderId: '380145632021',
    projectId: 'contac-app-new',
    authDomain: 'contac-app-new.firebaseapp.com',
    storageBucket: 'contac-app-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEzVlByM3JWUqk7bGCyVJXkSdp4Aw9Yr0',
    appId: '1:380145632021:android:5b3034565181f9ce385f1c',
    messagingSenderId: '380145632021',
    projectId: 'contac-app-new',
    storageBucket: 'contac-app-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWj_gd0IN4a_tuuJwFZZ5BRh7wssp4ijQ',
    appId: '1:380145632021:ios:cac212872290c788385f1c',
    messagingSenderId: '380145632021',
    projectId: 'contac-app-new',
    storageBucket: 'contac-app-new.appspot.com',
    iosBundleId: 'com.example.contactApp',
  );
}
